[package]
name = "rproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.6"
futures = "0.3.21"
tokio = { version = "1.17.0", features = ["full", "tracing"] }
